### ISSUE TITLE
Epic: Home page & Routing

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#1]
# Home page

Feature: Home page

## Epic Description

Complete all features of the home

## List of Tasks (Complete in order)

- [ ] Create landing page
- [x] Complete basic routing
- [ ] Add featured categories on landing page
