### ISSUE TITLE
Feature: Homepage Revamp

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#11]
# Homepage revamp

Feature: Homepage revamp

## Epic Description

This Feature will revamp the current homepage of the app

## List of Tasks (Complete in order)

- [x] Add hero section for homepage
- [x] Add filter by categories feature
- [x]  Add CTA for product page
- [x] Clicking on particular brand should take us to product page and filter should be applied by that brand
