### ISSUE TITLE
Epic: Product listing page

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#2]
# Product listing page

Feature: Product listing page

## Epic Description

This Feature will complete the product listing page, with filters and products card.

### Home page

- [ ] Show all products
- [ ] Product card should contain add to cart
- [ ] Product card should contain wishlist button

### Filters

- [ ] Price
- [ ] Category
- [ ] Rating
- [ ] Clear filters button
