### ISSUE TITLE
Epic: Cart Management

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#3]
# Epic Cart Management

Feature: Cart Management

## Epic Description

This Feature will add cart management in our e-comm app

## List of Tasks (Complete in order)

- [ ] Cart icon should take to carts page
- [ ] In the product card, quantity of that specific product should be shown
- [ ] Option to increase or decrease quantity of products
- [ ] Remove from cart button
- [ ] Adding to wishlist button
- [ ] Total price of all products should update on removing, adding, increasing or decreasing the quantity of products
- [ ] Price details card of the cart containing a button to checkout which will show the total price of the products with its quantity.
