### ISSUE TITLE
Epic: Wishlist management

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#4]
# Epic Wishlist Management

Feature: Wishlist Management

## Epic Description

This Feature will add wishlist management in our e-comm app

## List of Tasks (Complete in order)

- [ ] Wishlist icon should take to wishlist page
- [ ] Remove from wishlist button
- [ ] Adding to cart button
- [ ] If the cart already contains that item, it's only increasing the quantity.
