### ISSUE TITLE
Epic: Authentication 

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#5]
# Frontend Authentication

Feature: Awesome Feature Title

## Epic Description

This Feature will add an authentication feature to the e-commerce app

### Sign-up Page

- [ ] I can see a sign-up page from where I can sign-up using my email, first name, last name, password & confirm password.
- [ ] I can see a hide-show icon button that shows or hides my password.

### Login Page

- [ ] Login using email and password

### Logout

- [ ] If logged in show logout button in the navbar

**Comment by Pratham82** [comment]
Changes are done in #13
