### ISSUE TITLE
Epic: Feature improvements

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/snkr-town#9]
# Feature improvements

Feature: feature enhancements

## Epic Description

This Feature will add more functionality and UI elements to the current list of features

## List of Tasks (Complete in order)

- [ ] Add a loader component in homepage
- [ ] Add remove all products in the cart and wishlist
- [ ] Add Section names in the cart and wishlist
- [ ] Add the total items count on the product listing page
- [ ] Convert current sidebar to collapsable sidebar
- [ ] Add 404 page
- [ ] Add custom/ 3rd party alerts for add/remove/update product features
- [ ] Add page titles for all pages
